require_relative '../bundle/bundler/setup'

require 'repla/test'
require Repla::Test::HELPER_FILE
require Repla::Test::REPLA_FILE

require 'shellwords'

task default: ['jekyll:tests']

namespace :jekyll do
  task tests: [:clean_up]

  task :test_runner do
    tests_file = File.join(__dir__, 'tc_runner.rb')
    ruby Shellwords.escape(tests_file)
  end

  task clean_up: [:test_runner] do
  end
end
